---

- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - /Users/jake/rubrik/ansible/jake.vault
  vars:
    vm_name: sand1-jake-l1

  tasks:
    - name: On-Demand Snapshot
      rubrikinc.cdm.rubrik_on_demand_snapshot:
        object_name: "{{ vm_name }}"
        provider: "{{ rubrik_provider }}"
